services_choices = [
    ('adobe', 'Adobe'),
    ('airbnb', 'Airbnb'),
    ('amazon', 'Amazon'),
    ('american_express', 'American Express'),
    ('apple', 'Apple'),
    ('prime_video', 'Amazon Prime Video'),
    ('aws', 'AWS'),
    ('banco_do_brasil', 'Banco do Brasil'),
    ('booking', 'Booking'),
    ('caixa', 'Caixa'),
    ('deezer', 'Deezer'),
    ('discord', 'Discord'),
    ('disney+', 'Disney'),
    ('epic_games', 'Epic Games'),
    ('facebook', 'Facebook'),
    ('github', 'Github'),
    ('google', 'Google'),
    ('gov_br', 'Gov BR'),
    ('heroku', 'Heroku'),
    ('instagram', 'Instagram'),
    ('kayak', 'Kayak'),
    ('linkedin', 'LinkedIn'),
    ('magalu', 'Magazine Luiza'),
    ('mastercard', 'Mastercard'),
    ('mercado_livre', 'Mercado Livre'),
    ('netflix', 'Netflix'),
    ('notion', 'Notion'),
    ('nubank', 'Nubank'),
    ('nu_invest', 'Nu Invest'),
    ('outlook', 'Outlook'),
    ('paypal', 'Paypal'),
    ('pinterest', 'Pinterest'),
    ('reddit', 'Reddit'),
    ('santander', 'Santander'),
    ('spotify', 'Spotify'),
    ('steam', 'Steam'),
    ('stripe', 'Stripe'),
    ('submarino', 'Submarino'),
    ('trello', 'Trello'),
    ('trip_advisor', 'Trip Advisor'),
    ('twitch', 'Twitch'),
    ('twitter', 'Twitter'),
    ('vercel', 'Vercel'),
    ('visa', 'Visa'),
    ('wordpress', 'Wordpress'),
    ('yahoo', 'Yahoo'),
]


cards_choices = [
    ('Débito', 'Débito'),
    ('Crédito', 'Crédito'),
    ('Pré-pago', 'Pré-pago'),
    ('Co-branded', 'Co-branded'),
]